/* Generated by cbindgen.  Do not edit manually. */

#ifndef EMACS_RUST_DYNLIB_H
#define EMACS_RUST_DYNLIB_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Opaque handle type used by the C implementation.
 */
typedef void *DynlibHandle;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Lightweight probe invoked from C to ensure the Rust archive links in.
 */
void emacs_rust_dynlib_probe(void);

DynlibHandle emacs_rust_dynlib_open(const char *path);

DynlibHandle emacs_rust_dynlib_open_for_eln(const char *path);

int emacs_rust_dynlib_close(DynlibHandle handle);

const char *emacs_rust_dynlib_error(void);

void *emacs_rust_dynlib_sym(DynlibHandle handle, const char *symbol);

void (*emacs_rust_dynlib_func(DynlibHandle handle, const char *symbol))(void);

void emacs_rust_dynlib_addr(void (*funcptr)(void), const char **file, const char **sym);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* EMACS_RUST_DYNLIB_H */
