/* Generated by cbindgen.  Do not edit manually. */

#ifndef EMACS_RUST_SQLITE_H
#define EMACS_RUST_SQLITE_H

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Tag describing a scalar SQLite value.
 */
typedef enum EmacsSqliteValueTag {
  Null = 0,
  Integer = 1,
  Float = 2,
  Text = 3,
  Blob = 4,
} EmacsSqliteValueTag;

/**
 * Opaque handle type exchanged with the C side.
 */
typedef void *DynlibHandle;

typedef struct EmacsSqliteHandle {
  void *raw;
} EmacsSqliteHandle;

/**
 * Result structure shared with the C shim.
 */
typedef struct EmacsSqliteResult {
  /**
   * Zero indicates success; SQLite error codes are propagated as-is.
   */
  int code;
  /**
   * Optional UTF-8 error message owned by a thread-local scratch buffer.
   */
  const char *message;
} EmacsSqliteResult;

/**
 * Simple value representation exchanged with the C layer.  For `Text` and
 * `Blob`, the data pointer references memory managed by the Rust side and
 * remains valid until the next call that touches the same statement handle.
 */
typedef struct EmacsSqliteValue {
  enum EmacsSqliteValueTag tag;
  int64_t int_value;
  double float_value;
  const uint8_t *bytes_ptr;
  size_t bytes_len;
} EmacsSqliteValue;

/**
 * Helper describing a UTF-8 string slice returned to C.
 */
typedef struct EmacsSqliteString {
  const char *data;
  size_t len;
} EmacsSqliteString;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Lightweight probe invoked from C to ensure the Rust archive links in.
 */
void emacs_rust_dynlib_probe(void);

DynlibHandle emacs_rust_dynlib_open(const char *path);

DynlibHandle emacs_rust_dynlib_open_for_eln(const char *path);

int emacs_rust_dynlib_close(DynlibHandle handle);

const char *emacs_rust_dynlib_error(void);

void *emacs_rust_dynlib_sym(DynlibHandle handle, const char *symbol);

void (*emacs_rust_dynlib_func(DynlibHandle handle, const char *symbol))(void);

void emacs_rust_dynlib_addr(void (*funcptr)(void), const char **file, const char **sym);

/**
 * Ensure the Rust archive links in.
 */
void emacs_rust_sqlite_probe(void);

bool emacs_rust_sqlite_is_available(void);

struct EmacsSqliteHandle *emacs_rust_sqlite_open(const char *path,
                                                 bool readonly,
                                                 bool disable_uri,
                                                 struct EmacsSqliteResult *out);

int emacs_rust_sqlite_close(struct EmacsSqliteHandle *handle, struct EmacsSqliteResult *out);

struct EmacsSqliteHandle *emacs_rust_sqlite_prepare(struct EmacsSqliteHandle *handle,
                                                    const char *query,
                                                    const struct EmacsSqliteValue *values,
                                                    size_t value_len,
                                                    struct EmacsSqliteResult *out);

int emacs_rust_sqlite_step(struct EmacsSqliteHandle *handle,
                           struct EmacsSqliteValue *out_values,
                           size_t capacity,
                           size_t *out_count,
                           struct EmacsSqliteResult *out);

bool emacs_rust_sqlite_more(struct EmacsSqliteHandle *handle);

void emacs_rust_sqlite_columns(struct EmacsSqliteHandle *handle,
                               struct EmacsSqliteString *out_columns,
                               size_t capacity,
                               size_t *out_count);

int emacs_rust_sqlite_finalize(struct EmacsSqliteHandle *handle, struct EmacsSqliteResult *out);

int emacs_rust_sqlite_execute(struct EmacsSqliteHandle *handle,
                              const char *query,
                              const struct EmacsSqliteValue *values,
                              size_t value_len,
                              int64_t *out_changes,
                              struct EmacsSqliteResult *out);

int emacs_rust_sqlite_execute_batch(struct EmacsSqliteHandle *handle,
                                    const char *statements,
                                    struct EmacsSqliteResult *out);

struct EmacsSqliteString emacs_rust_sqlite_version(struct EmacsSqliteResult *out);

int emacs_rust_sqlite_load_extension(struct EmacsSqliteHandle *handle,
                                     const char *path,
                                     const char *symbol,
                                     struct EmacsSqliteResult *out);

int64_t emacs_rust_sqlite_changes(struct EmacsSqliteHandle *handle);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* EMACS_RUST_SQLITE_H */
